config/routes.rb
Rails.application.routes.draw do
  root to: 'talks#index'
  resources :talks, only: [:index,:show] do
   resources :hotsprings,only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :talk

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '秋田県'},
    {id: 4, name: '山形県'}, {id: 5, name: '岩手県'}, {id: 6, name: '宮城県'},
    {id: 7, name: '福島県'}, {id: 8, name: '愛知県'}, {id: 9, name: '岐阜県'},
    {id: 10, name: '静岡県'}, {id: 11, name: '三重県'}, {id: 12, name: '新潟県'},
    {id: 13, name: '山梨県'}, {id: 14, name: '長野県'}, {id: 15, name: '石川県'},
    {id: 16, name: '富山県'}, {id: 17, name: '福井県'}, {id: 18, name: '岡山県'},
    {id: 19, name: '広島県'}, {id: 20, name: '鳥取県'}, {id: 21, name: '島根県'},
    {id: 22, name: '山口県'}, {id: 23, name: '香川県'}, {id: 24, name: '徳島県'},
    {id: 25, name: '愛媛県'}, {id: 26, name: '高知県'}, {id: 27, name: '東京都'},
    {id: 28, name: '神奈川県'}, {id: 29, name: '埼玉県'}, {id: 30, name: '千葉県'},
    {id: 31, name: '栃木県'}, {id: 32, name: '茨城県'}, {id: 33, name: '群馬県'},
    {id: 34, name: '大阪府'}, {id: 35, name: '兵庫県'}, {id: 36, name: '京都府'},
    {id: 37, name: '滋賀県'}, {id: 38, name: '奈良県'}, {id: 39, name: '和歌山県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]

              include ActiveHash::Associations
              has_many :talks
              has_many :comments
end

app/models/talk.rb
class Talk < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(comment_params)
     #redirect_to "/talks/#{comment.talk.id}"  
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(talk_id: params[:talk_id],prefecture_id: params[:prefecture_id])
  end
end

app/controllers/hotsprings_controller.rb
class HotspringsController < ApplicationController
  def index
    @prefecture = Prefecture.find(params[:talk_id])
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
    prefecture = Prefecture.all
  end

  def show
    @prefecture = Prefecture.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotsprings_helper.rb
module HotspringsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/hotsprings/index.html.erb
  <div class='hotspringIndexHeader'>
    <nav class='navber navber-expand navbar-light hotspringIndexHeaderNave'>
    </nav>
  </div>

  <h1><%= @prefecture.name %></h1>

  <div class="main">    
        <div class="row">
          <div class="col-md-7 order-md-2">
            <h2>草津温泉にきました！</h2>
            <p>Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-3 order-md-1" style="width: 10rem;">
            <%= image_tag 'hotspring.jpg' ,class: 'card-img-top' %>
          </div>
          </div>

          <hr>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pakupakutalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/talks/index.html.erb
<div class='talkIndex'>
  <div class='talkIndexHeader'>
    <nav class='navber navber-expand navbar-light talkIndexHeaderNave'>
      <%= image_tag 'logo-6.png', class: 'img-fuild' %>
    </nav>
  </div>

  <div class='container'>
    <h4>エリアを選択</h4>
    <div class='row'>

      <div class='col-6 talkIndexArea'>
        <dl>
          <dt>北海道・東北</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '北海道', talk_path(id:1), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '青森', talk_path(id:2), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '秋田', talk_path(id:3), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '山形', talk_path(id:4), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '岩手', talk_path(id:5), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '宮城', talk_path(id:6), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '福島', talk_path(id:7), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
        <dl>
          <dt>中部</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '愛知', talk_path(id:8), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '岐阜', talk_path(id:9), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '静岡', talk_path(id:10), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '三重', talk_path(id:11), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '新潟', talk_path(id:12), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '山梨', talk_path(id:13), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '長野', talk_path(id:14), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '石川', talk_path(id:15), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '富山', talk_path(id:16), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '福井', talk_path(id:17), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
        <dl>
          <dt>中国・四国</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '岡山', talk_path(id:18), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '広島', talk_path(id:19), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '鳥取', talk_path(id:20), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '島根', talk_path(id:21), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '山口', talk_path(id:22), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '香川', talk_path(id:23), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '徳島', talk_path(id:24), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '愛媛', talk_path(id:25), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '高知', talk_path(id:26), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
      </div>

      <div class='col-6 talkIndexArea'>
        <dl>
          <dt>関東</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '東京', talk_path(id:27), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '神奈川', talk_path(id:28), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '埼玉', talk_path(id:29), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '千葉', talk_path(id:30), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '栃木', talk_path(id:31), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '茨城', talk_path(id:32), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '群馬', talk_path(id:33), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
        <dl>
          <dt>関西</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '大阪', talk_path(id:34), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '兵庫', talk_path(id:35), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '京都', talk_path(id:36), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '滋賀', talk_path(id:37), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '奈良', talk_path(id:38), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '和歌山', talk_path(id:39), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
        <dl>
          <dt>九州・沖縄</dt>
          <dd>
            <ul class='nav'>
              <li class='nav-item'><%= link_to '福岡', talk_path(id:40), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '佐賀', talk_path(id:41), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '長崎', talk_path(id:42), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '熊本', talk_path(id:43), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '大分', talk_path(id:44), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '宮崎', talk_path(id:45), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '鹿児島', talk_path(id:46), class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to '沖縄', talk_path(id:47), class: 'nav-link' %></li>
            </ul>
          </dd>
        </dl>
      </div>

    </div>
  </div>
</div>

app/views/talks/show.html.erb
<h1><%= @prefecture.name%></h1>


<div class="catego">
<div class="card" style="width: mb-3;">
  <%= image_tag 'hotspring.jpg' ,class: 'card-img-top' %>
  <div class="card-body">
    <h1 class="card-text"><%= link_to '温泉',  talk_hotsprings_path(params[:id]) %></h1>
  </div>
</div>

<div class="card " style="width: mb-3;">
  <%= image_tag 'camp.jpg' ,class: 'card-img-top' %>
  <div class="card-body">
    <h1 class="card-text "><a href="#">キャンプ</a></h1>
  </div>
</div>

<div class="card" style="width: mb-3;">
  <%= image_tag 'eat.jpg' ,class: 'card-img-top' %>
  <div class="card-body">
    <h1 class="card-text"><a href="#">食事</a></h1>
  </div>
</div>

<div class="card" style="width: mb-3;">
  <%= image_tag 'zatudan.jpg' ,class: 'card-img-top' %>
  <div class="card-body">
    <h1 class="card-text"><a href="#">雑談</a></h1>
  </div>
</div>
</div>